### ISSUE TITLE
Website Beta Release

### ISSUE THREAD

**Issue by Noro07** [Noro07/General-Planning#1]
According to the requirement, we need to meet the following target before beta release:
- [ ] An edit page for user to upload his own new project( including photos and description );
- [ ] Support project viewer( including photos and description );
- [ ] Adapt to mobile;
- [ ] Adapt to table;
